Web/WebMVC/ViewModels/Application.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebMVC.Services.ModelDTOs;

namespace Microsoft.Fee.WebMVC.ViewModels
{
    public class Application
    {
        public string ApplicationNumber { get; set; }

        public DateTime Date { get; set; }

        public string Status { get; set; }

        public decimal Total { get; set; }

        public string Description { get; set; }
        [Required]
        public string DateofBirth { get; set; }
        [Required]
        public string IDNumber { get; set; }
        [Required]
        public decimal Request { get; set; }
        [Required]
        public int GenderId { get; set; }
        [Required]
        public int HobbyId { get; set; }
        [Required]
        public int LocationIdId { get; set; }
        [Required]
        public int SchoolId { get; set; }

        public int PaymentTypeId { get; set; }

        public string Student { get; set; }

        public List<SelectListItem> ActionCodeSelectList =>
           GetActionCodesByCurrentState();

        // See the property initializer syntax below. This
        // initializes the compiler generated field for this
        // auto-implemented property.
        public List<ApplicationItem> ApplicationItems { get; } = new List<ApplicationItem>();

        [Required]
        public Guid RequestId { get; set; }

        private List<SelectListItem> GetActionCodesByCurrentState()
        {
            var actions = new List<ApplicationProcessAction>();
            switch (Status?.ToLower())
            {
                case "paid":
                    actions.Add(ApplicationProcessAction.Grant);
                    break;
            }

            var result = new List<SelectListItem>();
            actions.ForEach(action =>
            {
                result.Add(new SelectListItem { Text = action.Name, Value = action.Code });
            });

            return result;
        }
    }

    public enum paymentType
    {
        MPesa = 1
    }
}

Web/WebMVC/ViewModels/ApplicationItem.cs
namespace Microsoft.Fee.WebMVC.ViewModels
{
    public record ApplicationItem
    {
        public int ScholarshipItemId { get; init; }

        public string ScholarshipItemName { get; init; }

        public decimal SlotAmount { get; init; }

        public int Slots { get; init; }

        public string PictureUrl { get; init; }
    }
}

Web/WebMVC/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Fee.WebMVC.Services;
using Microsoft.Fee.WebMVC.ViewModels;
using System;
using System.Threading.Tasks;

namespace Microsoft.Fee.WebMVC.Controllers
{
    [Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]
    public class ApplicationController : Controller
    {
        private IApplyingService _applicationSvc;
        private IBasketService _basketSvc;
        private readonly IIdentityParser<ApplicationUser> _appUserParser;
        public ApplicationController(IApplyingService applicationSvc, IBasketService basketSvc, IIdentityParser<ApplicationUser> appUserParser)
        {
            _appUserParser = appUserParser;
            _applicationSvc = applicationSvc;
            _basketSvc = basketSvc;
        }

        public async Task<IActionResult> Create()
        {

            var user = _appUserParser.Parse(HttpContext.User);
            var application = await _basketSvc.GetApplicationDraft(user.Id);
            var vm = _applicationSvc.MapUserInfoIntoApplication(user, application);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Application model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = _appUserParser.Parse(HttpContext.User);
                    var basket = _applicationSvc.MapApplicationToBasket(model);

                    await _basketSvc.Checkout(basket);

                    //Redirect to historic list.
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", $"It was not possible to create a new application, please try later on ({ex.GetType().Name} - {ex.Message})");
            }

            return View("Create", model);
        }

        public async Task<IActionResult> Cancel(string applicationId)
        {
            await _applicationSvc.CancelApplication(applicationId);

            //Redirect to historic list.
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(string applicationId)
        {
            var user = _appUserParser.Parse(HttpContext.User);

            var application = await _applicationSvc.GetApplication(user, applicationId);
            return View(application);
        }

        public async Task<IActionResult> Index(Application item)
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var vm = await _applicationSvc.GetMyApplications(user);
            return View(vm);
        }
    }
}

Web/WebMVC/Views/Application/Create.cshtml
@using Microsoft.Fee.WebMVC.Services
@model Microsoft.Fee.WebMVC.ViewModels.Application
@inject IIdentityParser<ApplicationUser> UserManager

@{
     ViewData["Title"] = "New Application";
     var headerList= new List<Header>() {
       new Header() { Controller = "Cart", Text = "Back to cart" } };
}

<partial name="_Header" model="headerList"/>
<div class="container">
    <form method="post" asp-controller="Application" asp-action="Checkout">
        <section class="esh-applications_new-section">
            <div class="row">
                @foreach (var error in ViewData.ModelState.Values.SelectMany(err => err.Errors)) {
                    <div class="alert alert-warning" role="alert">                    
                        &nbsp;@error.ErrorMessage
                    </div>
                }
            </div>
        </section>
        <section class="esh-applications_new-section">
        </section>

        @await Html.PartialAsync("_ApplicationItems")

        <section class="esh-applications_new-section">
            <div class="form-group row">
                <div class="col-md-9">
                </div>
                <div class="col-md-2">
                    <input type="submit" value="[ Place Application ]" name="action" class="btn esh-applications_new-placeApplication" />
                </div>
            </div>
        </section>
        <input asp-for="RequestId" type="hidden" value="@Guid.NewGuid().ToString()"/>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/WebMVC/Views/Application/Detail.cshtml
@using Microsoft.Fee.WebMVC.ViewModels

@model Microsoft.Fee.WebMVC.ViewModels.Application

@{
     ViewData["Title"] = "Application Detail";
     var headerList= new List<Header>() {
     new Header() { Controller = "Scholarship", Text = "Back to scholarships" } };
}

<div class="f-applications_detail">
    <partial name="_Header" model="headerList"/>

    <div class="container">
        <section class="f-applications_detail-section">
            <article class="f-applications_detail-titles row">
                <section class="f-applications_detail-title col-3">Application number</section>
                <section class="f-applications_detail-title col-3">Date</section>
                <section class="f-applications_detail-title col-3">Total</section>
                <section class="f-applications_detail-title col-3">Status</section>
            </article>

            <article class="f-applications_detail-items row">
                <section class="f-applications_detail-item col-3">@Model.ApplicationNumber</section>
                <section class="f-applications_detail-item col-3">@Model.Date</section>
                <section class="f-applications_detail-item col-3">$@Model.Total</section>
                <section class="f-applications_detail-title col-3">@Model.Status</section>
            </article>
        </section>
        
        <section class="f-applications_detail-section">
            <article class="f-applications_detail-titles row">
                <section class="f-applications_detail-title col-12">Description</section>
            </article>

            <article class="f-applications_detail-items row">
                <section class="f-applications_detail-item col-12">@Model.Description</section>
            </article>
        </section>

        <section class="f-applications_detail-section">
            <article class="f-applications_detail-titles row">
                <section class="f-applications_detail-title col-12">APPLICATION DETAILS</section>
            </article>

            @for (int i = 0; i < Model.ApplicationItems.Count; i++)
            {
                var item = Model.ApplicationItems[i];
                <article class="f-applications_detail-items f-applications_detail-items--border row">
                    <section class="f-applications_detail-item col-md-4 hidden-md-down">
                        <img class="f-applications_detail-image" src="@item.PictureUrl">
                    </section>
                    <section class="f-applications_detail-item f-applications_detail-item--middle col-4">@item.ScholarshipItemName</section>
                    <section class="f-applications_detail-item f-applications_detail-item--middle col-1">$ @item.SlotAmount.ToString("N2")</section>
                    <section class="f-applications_detail-item f-applications_detail-item--middle col-1">@item.Slots</section>
                    <section class="f-applications_detail-item f-applications_detail-item--middle col-2">$ @Math.Round(item.Slots * item.SlotAmount, 2).ToString("N2")</section>
                </article>
            }
        </section>

        <section class="f-applications_detail-section f-applications_detail-section--right">
            <article class="f-applications_detail-titles f-basket-titles--clean row">
                <section class="f-applications_detail-title col-9"></section>
                <section class="f-applications_detail-title col-2">TOTAL</section>
            </article>

            <article class="f-applications_detail-items row">
                <section class="f-applications_detail-item col-9"></section>
                <section class="f-applications_detail-item f-applications_detail-item--mark col-2">$ @Model.Total.ToString("N2")</section>
            </article>
        </section>
    </div>
</div>

Web/WebMVC/Views/Application/Index.cshtml
@using Microsoft.Fee.WebMVC.ViewModels

@model IEnumerable<Microsoft.Fee.WebMVC.ViewModels.Application>

@{
     ViewData["Title"] = "My Applications";
     var headerList= new List<Header>() {
        new Header() { Controller = "Scholarship", Text = "Back to scholarships" },
        new Header() { Text = " / " },
        new Header() { Controller = "ApplicationManagement", Text = "Applications Management" } };
}

<div class="f-applications">
    <partial name="_Header" model="headerList"/>

    <div class="container">
        <article class="f-applications-titles row">
            <section class="f-applications-title col-2">Application number</section>
            <section class="f-applications-title col-4">Date</section>
            <section class="f-applications-title col-2">Total</section>
            <section class="f-applications-title col-2">Status</section>
            <section class="f-applications-title col-2"></section>
        </article>
        @if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                <article class="f-applications-items row">
                    <section class="f-applications-item col-2">@Html.DisplayFor(modelItem => item.ApplicationNumber)</section>
                    <section class="f-applications-item col-4">@Html.DisplayFor(modelItem => item.Date)</section>
                    <section class="f-applications-item col-2">$ @Html.DisplayFor(modelItem => item.Total)</section>
                    <section class="f-applications-item col-2">@Html.DisplayFor(modelItem => item.Status)</section>
                    <section class="f-applications-item col-1">
                        <a class="f-applications-link" asp-controller="Application" asp-action="Detail" asp-route-applicationId="@item.ApplicationNumber">Detail</a>
                    </section>
                    <section class="f-applications-item col-1">
                        @if (item.Status.ToLower() == "submitted")
                        {
                            <a class="f-applications-link" asp-controller="Application" asp-action="cancel" asp-route-applicationId="@item.ApplicationNumber">Cancel</a>
                        }
                    </section>
                </article>
            }
        }
    </div>
</div>

Web/WebMVC/Views/Application/_ApplicationItems.cshtml
@model Microsoft.Fee.WebMVC.ViewModels.Application


<section class="f-applications_new-section">
    <article class="f-applications_new-titles row">
        <section class="f-applications_new-title col-12">Application details</section>
    </article>

    @for (int i = 0; i < Model.ApplicationItems.Count; i++)
    {
        var item = Model.ApplicationItems[i];

        <article class="f-applications_new-items f-applications_new-items--border row">
            <section class="f-applications_new-item col-md-4 hidden-md-down">
                <img class="f-applications_new-image" src="@item.PictureUrl">
                <input type="hidden" value="@item.PictureUrl" name=@("applicationitems[" + i + "].PictureUrl") />
            </section>
            <section class="f-applications_new-item f-applications_new-item--middle col-4">
                @item.ScholarshipItemName
                <input type="hidden" value="@item.ScholarshipItemName" name=@("applicationitems[" + i + "].ScholarshipItemName") />
            </section>
            <section class="f-applications_new-item f-applications_new-item--middle col-1">
                $ @item.SlotAmount.ToString("N2")
                <input type="hidden" value="@item.SlotAmount" name=@("applicationitems[" + i + "].SlotAmount") />
            </section>
            <section class="f-applications_new-item f-applications_new-item--middle col-1">
                @item.Slots
                <input type="hidden" value="@item.Slots" name=@("applicationitems[" + i + "].Slots") />
            </section>
            <section class="f-applications_new-item f-applications_new-item--middle col-2">$ @Math.Round(item.Slots * item.SlotAmount, 2).ToString("N2")</section>
        </article>
    }
</section>

<section class="f-applications_new-section f-applications_new-section--right">
    <article class="f-applications_new-titles row">
        <section class="f-applications_new-title col-9"></section>
        <section class="f-applications_new-title col-2">Total</section>
    </article>

    <article class="f-applications_new-items row">
        <section class="f-applications_new-item col-9"></section>
        <section class="f-applications_new-item f-applications_new-item--mark col-2">
            $ @Model.Total.ToString("N2")
            <input type="hidden" value="@Model.Total" name="Total"/>
        </section>
    </article>
</section>