Web/WebMVC/ViewModels/Header.cs
namespace Microsoft.Fee.WebMVC.ViewModels
{
    public record Header
    {
        public string Controller { get; init; }
        public string Text { get; init; }
    }
}

Web/WebMVC/Controllers/ScholarshipController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Fee.WebMVC.Services;
using Microsoft.Fee.WebMVC.ViewModels.ScholarshipViewModels;
using Microsoft.Fee.WebMVC.ViewModels.Pagination;
using System;
using System.Threading.Tasks;

namespace Microsoft.Fee.WebMVC.Controllers
{
    public class ScholarshipController : Controller
    {
        private IScholarshipService _scholarshipSvc;

        public ScholarshipController(IScholarshipService scholarshipSvc) =>
            _scholarshipSvc = scholarshipSvc;

        public async Task<IActionResult> Index(int? LocationFilterApplied, int? EducationLevelFilterApplied, int? page, [FromQuery] string errorMsg)
        {
            var itemsPage = 10;
            var scholarship = await _scholarshipSvc.GetScholarshipItems(page ?? 0, itemsPage, LocationFilterApplied, EducationLevelFilterApplied);
            var vm = new IndexViewModel()
            {
                ScholarshipItems = scholarship.Data,
                Locations = await _scholarshipSvc.GetLocations(),
                EducationLevels = await _scholarshipSvc.GetEducationLevels(),
                LocationFilterApplied = LocationFilterApplied ?? 0,
                EducationLevelFilterApplied = EducationLevelFilterApplied ?? 0,
                PaginationInfo = new PaginationInfo()
                {
                    ActualPage = page ?? 0,
                    ItemsPerPage = scholarship.Data.Count,
                    TotalItems = scholarship.Count,
                    TotalPages = (int)Math.Ceiling(((decimal)scholarship.Count / itemsPage))
                }
            };

            vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
            vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

            ViewBag.BasketInoperativeMsg = errorMsg;

            return View(vm);
        }
    }
}

Web/WebMVC/Views/Shared/_Header.cshtml
@model IEnumerable<Microsoft.Fee.WebMVC.ViewModels.Header>

<div class="f-header">
    <div class="container">
        @foreach (var header in @Model)
        {
            <a class="f-header-back" asp-area="" asp-controller="@header.Controller" asp-action="Index">@header.Text</a>
        }
    </div>
</div>

Web/WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microsoft.Fee.WebMVC</title>

    <environment names="Development">
        <link rel="stylfeet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylfeet" href="~/css/app.css" />
        <link rel="stylfeet" href="~/css/app.component.css" />
        <link rel="stylfeet" href="~/css/shared/components/header/header.css" />
        <link rel="stylfeet" href="~/css/shared/components/identity/identity.css" />
        <link rel="stylfeet" href="~/css/shared/components/pager/pager.css" />
        <link rel="stylfeet" href="~/css/basket/basket.component.css" />
        <link rel="stylfeet" href="~/css/basket/basket-status/basket-status.component.css" />
        <link rel="stylfeet" href="~/css/scholarship/scholarship.component.css" />
        <link rel="stylfeet" href="~/css/applications/applications.component.css" />
        <link rel="stylfeet" href="~/css/applications/applications-detail/applications-detail.component.css" />
        <link rel="stylfeet" href="~/css/applications/applications-new/applications-new.component.css" />
        <link rel="stylfeet" href="~/css/override.css" type="text/css" />
        <link rel="stylfeet" href="~/css/site.min.css" type="text/css" />

    </environment>
    <environment names="Staging,Production">
        <link rel="stylfeet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylfeet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylfeet" href="~/css/override.css" type="text/css" />
    </environment>
</head>
<body>
    <header class="f-app-header">
        <div class="container">
            <article class="row">

                <section class="col-lg-7 col-md-6 col-12">
                    <a class="navbar-brand" routerLink="scholarship">
                        <a asp-area="" asp-controller="Scholarship" asp-action="Index">
                            <img src="~/images/brand.png" />
                        </a>
                    </a>
                </section>

                @await Html.PartialAsync("_LoginPartial")
            </article>
        </div>
    </header>

    @RenderBody()


    <footer class="f-app-footer">
        <div class="container">
            <article class="row">

                <section class="col-sm-6">
                    <img class="f-app-footer-brand" src="~/images/brand_dark.png" />
                </section>

                <section class="col-sm-6">
                    <img class="f-app-footer-text hidden-xs" src="~/images/main_footer_text.png" width="335" height="26" alt="footer text image" />
                </section>

            </article>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)


    @using Microsoft.AspNetCore.Authentication;
    @using Microsoft.Extensions.Options
    @inject IOptions<Microsoft.Fee.WebMVC.AppSettings> settings

    <script type="text/javascript">
        if ('@User.Identity.IsAuthenticated' === 'True') {
            var timerId;

            stablishConnection((conn) => registerNotificationHandlers(conn));                                  
        }

        function stablishConnection(cb) {
            let connection = new signalR.HubConnectionBuilder()
                .withUrl('@settings.Value.SignalrHubUrl/hub/notificationhub', {
                    accessTokenFactory: () => {
                        return "Authorization", getToken();
                    }
                })
                .withAutomaticReconnect()
                .build(); 
            
            connection.start().then(function () {
                console.log('User Registered to Signalr Hub');
                cb(connection);
            });       
        }

        function registerNotificationHandlers(connection) {
            connection.on("UpdatedApplicationState", (message) => {
                toastr.success('Updated to status: ' + message.status, 'Application Id: ' + message.applicationId);
                if (window.location.pathname.split("/").pop() === 'Application') {
                    refrfApplicationList();
                }
            });
        }

        function getToken() {
            return '@Context.GetTokenAsync("access_token").Result';
        }

        function refrfApplicationList() {
            clearTimeout(timerId);
            timerId = setTimeout(function () {
                window.location.reload();
            }, 1000);
        }
    </script>
</body>
</html>